"""Training integration contracts for CodeVerifier."""

from code_verifier.training.grpo import (
    GRPOCheckpointIdentity,
    GRPORefreshBinding,
    GRPOTrainingConfig,
    GRPOTrainingError,
    GRPOTrainingSummary,
    build_grpo_reward_callback,
    grpo_evaluation_checkpoint_id,
    grpo_run_directory,
    grpo_training_config_from_mapping,
    load_completed_grpo_checkpoint,
    load_grpo_refresh_binding,
    load_grpo_training_config,
    run_grpo_training,
    validate_grpo_artifact_pair,
    validate_grpo_config_pair,
    validate_grpo_training_hardware,
)
from code_verifier.training.grpo_data import GRPODataError, build_grpo_dataset
from code_verifier.training.sft import (
    SFTCheckpointIdentity,
    SFTTrainingConfig,
    SFTTrainingError,
    SFTTrainingSummary,
    load_completed_sft_checkpoint,
    load_sft_training_config,
    run_sft_training,
    validate_sft_training_hardware,
)
from code_verifier.training.sft_data import (
    SFTDataError,
    SFTExample,
    build_prevalidated_sft_dataset,
    build_sft_dataset,
    validate_sft_record,
)
from code_verifier.training.sft_prevalidation import (
    SFTPrevalidationError,
    SFTPrevalidationEvidence,
    SFTPrevalidationSummary,
    run_sft_prevalidation,
    validate_sft_prevalidation_manifest,
)

__all__ = [
    "GRPOCheckpointIdentity",
    "GRPODataError",
    "GRPORefreshBinding",
    "GRPOTrainingConfig",
    "GRPOTrainingError",
    "GRPOTrainingSummary",
    "SFTCheckpointIdentity",
    "SFTDataError",
    "SFTExample",
    "SFTPrevalidationError",
    "SFTPrevalidationEvidence",
    "SFTPrevalidationSummary",
    "SFTTrainingConfig",
    "SFTTrainingError",
    "SFTTrainingSummary",
    "build_grpo_dataset",
    "build_grpo_reward_callback",
    "build_prevalidated_sft_dataset",
    "build_sft_dataset",
    "grpo_evaluation_checkpoint_id",
    "grpo_run_directory",
    "grpo_training_config_from_mapping",
    "load_completed_grpo_checkpoint",
    "load_completed_sft_checkpoint",
    "load_grpo_refresh_binding",
    "load_grpo_training_config",
    "load_sft_training_config",
    "run_grpo_training",
    "run_sft_prevalidation",
    "run_sft_training",
    "validate_grpo_artifact_pair",
    "validate_grpo_config_pair",
    "validate_grpo_training_hardware",
    "validate_sft_prevalidation_manifest",
    "validate_sft_record",
    "validate_sft_training_hardware",
]
from code_verifier.training.calibration import (
    CalibrationClass,
    CalibrationConfig,
    CalibrationError,
    CalibrationGenerationRecord,
    CalibrationGenerationSummary,
    CalibrationInputRecord,
    CalibrationPoolSummary,
    build_calibrated_active_pool,
    calibration_problem_seed,
    check_calibrated_active_pool,
    load_calibration_config,
    load_completed_calibration_generation,
    prepare_calibration_input_bundle,
    run_calibration_generation,
    score_calibration_generation,
)

__all__ += [
    "CalibrationClass",
    "CalibrationConfig",
    "CalibrationError",
    "CalibrationGenerationRecord",
    "CalibrationGenerationSummary",
    "CalibrationInputRecord",
    "CalibrationPoolSummary",
    "build_calibrated_active_pool",
    "calibration_problem_seed",
    "check_calibrated_active_pool",
    "load_calibration_config",
    "load_completed_calibration_generation",
    "prepare_calibration_input_bundle",
    "run_calibration_generation",
    "score_calibration_generation",
]
